"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "bn";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, defaultText?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    lang_name: "English",
    bangla: "Bangla",
    english: "English",
    become_seller: "Become a Seller",
    start_seller: "Start Seller",
    help_support: "Help & Support",
    help: "Help",
    app: "App",
    join_affiliate: "Join Affiliate",
    login: "Login",
    register: "Register",
    categories: "Categories",
    shop_by_category: "Shop by Category",
    explore_categories: "Explore Categories",
    search_placeholder: "Search products, brands, suppliers & categories...",
    track_order: "Track My Order",
    profile: "Profile",
    dashboard: "Dashboard",
    logout: "Logout",
    account: "Account",
    search: "Search",
    all_categories: "All Categories",
    taka: "Taka",
    cart: "Cart",
    wishlist: "Wishlist",
    compare: "Compare",
    home: "Home",
    shop: "Shop",
    deals: "Deals",
    flash_sale: "Flash Sale",
    all_brands: "All Brands",
    new_arrivals: "New Arrivals",
    best_sellers: "Best Sellers",
    weekly_best_product: "Weekly Best Product",
    featured_products: "Featured Products",
    hot_deals: "Hot Deals",
    deals_of_the_day: "Deals Of The Day",
    weekly_top_vendors: "Weekly Top Vendors",
    featured_sellers: "Featured Sellers",
    top_verified_stores: "Top Verified Stores",
    explore_stores: "Explore Stores",
    visit_store: "Visit Store",
    view_all: "VIEW ALL PRODUCTS",
    view_all_short: "View All",
    see_more: "See More",
    see_more_products: "See More Products",
    shop_more: "Shop More",
    shop_now: "SHOP NOW",
    shop_collection: "Shop Collection",
    claim_deal: "Claim Deal",
    add_to_cart: "Add To Cart",
    add_to_wishlist: "Add to Wishlist",
    remove_from_wishlist: "Remove from Wishlist",
    add_to_compare: "Add to Compare",
    remove_from_compare: "Remove from Compare",
    out_of_stock: "Out of Stock",
    in_stock: "In Stock",
    sold: "Sold",
    available: "Available",
    ending_in: "Ending in",
    hurry_up: "Hurry Up! Offer Ends In:",
    days: "Days",
    hours: "Hours",
    mins: "Mins",
    secs: "Secs",
    off: "OFF",
    free_shipping: "Free Shipping on Orders Over ৳1,000",
    customer_support: "24/7 Customer Support",
    trusted_badge: "Trusted by 20,000+ Happy Customers",
    my_account: "My Account",
    all: "All",
    products: "Products",
    suppliers: "Suppliers",
    recent_searches: "Recent Searches",
    clear: "Clear",
    trending_searches: "Trending Searches",
    no_results_found: "No results found",
    free_delivery: "FREE DELIVERY",
    from_min: "From ৳1,000",
    support_24_7: "SUPPORT 24/7",
    online_24_hours: "Online 24 Hours",
    free_return: "FREE RETURN",
    return_policy: "365 A Day",
    payment_method: "PAYMENT METHOD",
    secure_payment: "Secure Payment",
    big_saving: "BIG SAVING",
    weekend_sales: "Weekend Sales",
    address: "Address",
    address_val: "Uttara, Dhaka, Bangladesh",
    call_us: "Call us",
    mail: "Mail",
    hours_label: "Hours",
    company: "Company",
    about_us: "About Us",
    delivery_info: "Delivery Information",
    privacy_policy: "Privacy Policy",
    data_deletion: "Data Deletion",
    terms_conditions: "Terms & Conditions",
    contact_us: "Contact Us",
    support_center: "Support Center",
    corporate: "Corporate",
    become_vendor: "Become a Vendor",
    affiliate_program: "Affiliate Program",
    farm_business: "Farm Business",
    farm_careers: "Farm Careers",
    our_suppliers: "Our Suppliers",
    accessibility: "Accessibility",
    promotions: "Promotions",
    popular: "Popular",
    install_app: "Install App",
    from_app_store: "From App Store or Google Play",
    secured_payment_gateways: "Secured Payment Gateways",
    copyright: "All rights reserved",
    mens_tshirt: "Men's T-Shirts & Polos",
    mens_pant: "Men's Pants & Trousers",
    electronics: "Electronics & Gadgets",
    fashion: "Fashion & Apparel",
    watches: "Watches & Jewelry",
    laptops: "Laptops & Tech",
    beauty: "Beauty & Skincare",
    audio: "Headphones & Audio",
    smartphones: "Smartphones",
    footwear: "Footwear",
    groceries: "Groceries",
    home_living: "Home & Living",
    super_discount: "SUPER DISCOUNT",
    summer_discount: "80% DISCOUNT ONLY THIS SUMMER",
    exclusive_audio: "EXCLUSIVE AUDIO SALE",
    studio_headsets: "STUDIO HEADSETS",
    luxury_watches: "LUXURY SMART WATCHES",
    with_buying_fridge: "WITH BUYING FRIDGE",
    discount: "DISCOUNT",
    sale_up_to_60: "Sale up to 60% on 50+ products in clude wedding flower",
    explore_now: "Explore Now",
    buy_now: "Buy Now",
    spring_season: "Spring Season",
    first_order: "FOR THE FIRST ORDER",
    cameras: "CAMERA",
    everything: "EVERYTHING!",
    case_iphone: "CASE IPHONE FOR 2018",
    sitewide: "SITEWIDE *",
    promo_code: "PROMO CODE",
    time: "TIME",
    cart_summary_msg: "You're just a few steps away from completing your order.",
    cart_empty_msg: "Your cart is currently empty. Start shopping to add some items!",
    cart_empty: "Empty Basket",
    cart_empty_sub: "Add products from the catalog to see them here.",
    price: "Price",
    subtotal: "Subtotal",
    total_items: "Total Items",
    units: "Units",
    total_price: "Total Price",
    checkout: "Proceed to Checkout",
    view_full_cart: "View Full Cart",
    tax_shipping_note: "Tax and shipping will be calculated during checkout.",
    wishlist_empty: "Your wishlist is empty",
    save_items_love: "Save items you love to your wishlist and shop them later",
    start_shopping: "Start Shopping",
    item: "item",
    items: "items",
    clear_all: "Clear All",
    removed_from_wishlist: "Removed from wishlist",
    moved_to_cart: "Moved to cart",
    wishlist_cleared: "Wishlist cleared",
    no_categories_found: "No categories found",
    view_all_categories: "View All Categories",
    menu: "Menu",
  },
  bn: {
    lang_name: "বাংলা",
    bangla: "বাংলা",
    english: "English",
    become_seller: "সেলার হোন",
    start_seller: "সেলার শুরু করুন",
    help_support: "সাহায্য ও সাপোর্ট",
    help: "সাহায্য",
    app: "অ্যাপ",
    join_affiliate: "অ্যাফিলিয়েট",
    login: "লগইন",
    register: "রেজিস্ট্রেশন",
    categories: "ক্যাটাগরি",
    shop_by_category: "ক্যাটাগরি অনুযায়ী কেনাকাটা",
    explore_categories: "ক্যাটাগরি দেখুন",
    search_placeholder: "পণ্য, ব্র্যান্ড, সরবরাহকারী ও ক্যাটাগরি খুঁজুন...",
    track_order: "অর্ডার ট্র্যাক করুন",
    profile: "প্রোফাইল",
    dashboard: "ড্যাশবোর্ড",
    logout: "লগআউট",
    account: "অ্যাকাউন্ট",
    search: "অনুসন্ধান",
    all_categories: "সকল ক্যাটাগরি",
    taka: "টাকা",
    cart: "কার্ট",
    wishlist: "উইশলিস্ট",
    compare: "তুলনা",
    home: "হোম",
    shop: "শপ",
    deals: "অফারসমূহ",
    flash_sale: "ফ্ল্যাশ সেল",
    all_brands: "সকল ব্র্যান্ড",
    new_arrivals: "নতুন পণ্য",
    best_sellers: "সেরা বিক্রিত",
    weekly_best_product: "সাপ্তাহিক সেরা পণ্য",
    featured_products: "বিশেষ পণ্যসমূহ",
    hot_deals: "হট ডিলস",
    deals_of_the_day: "দিনের সেরা ডিল",
    weekly_top_vendors: "সাপ্তাহিক সেরা ভেন্ডর",
    featured_sellers: "সেরা সেলারসমূহ",
    top_verified_stores: "ভেরিফায়েড টপ স্টোর",
    explore_stores: "স্টোরসমূহ দেখুন",
    visit_store: "স্টোরে যান",
    view_all: "সব পণ্য দেখুন",
    view_all_short: "সব দেখুন",
    shop_more: "আরও দেখুন",
    shop_now: "এখনই কিনুন",
    shop_collection: "কালেকশন দেখুন",
    claim_deal: "ডিলটি নিন",
    add_to_cart: "কার্টে যোগ করুন",
    add_to_wishlist: "উইশলিস্টে যোগ করুন",
    remove_from_wishlist: "উইশলিস্ট থেকে মুছুন",
    add_to_compare: "তুলনা তালিকায় যোগ করুন",
    remove_from_compare: "তুলনা তালিকা থেকে মুছুন",
    out_of_stock: "স্টক শেষ",
    in_stock: "স্টকে আছে",
    sold: "বিক্রি হয়েছে",
    available: "মজুদ আছে",
    ending_in: "শেষ হতে বাকি",
    hurry_up: "দেরি করবেন না! অফার শেষ হতে বাকি:",
    days: "দিন",
    hours: "ঘন্টা",
    mins: "মিনিট",
    secs: "সেকেন্ড",
    off: "ছাড়",
    free_shipping: "৳১,০০০ টাকার বেশি অর্ডারে ফ্রি ডেলিভারি",
    customer_support: "২৪/৭ কাস্টমার সাপোর্ট",
    trusted_badge: "২০,০০০+ সন্তুষ্ট গ্রাহকের বিশ্বাস",
    my_account: "আমার অ্যাকাউন্ট",
    all: "সব",
    products: "পণ্যসমূহ",
    suppliers: "সাপ্লায়ার",
    recent_searches: "সাম্প্রতিক অনুসন্ধান",
    clear: "মুছুন",
    trending_searches: "জনপ্রিয় অনুসন্ধান",
    no_results_found: "কোন ফলাফল পাওয়া যায়নি",
    free_delivery: "ফ্রি ডেলিভারি",
    from_min: "সর্বনিম্ন ৳১,০০০ থেকে",
    support_24_7: "২৪/৭ সাপোর্ট",
    online_24_hours: "২৪ ঘণ্টা অনলাইন",
    free_return: "ফ্রি রিটার্ন",
    return_policy: "৩৬৫ দিন রিটার্ন পলিসি",
    payment_method: "পেমেন্ট মাধ্যম",
    secure_payment: "১০০% নিরাপদ পেমেন্ট",
    big_saving: "বিশাল ছাড়",
    weekend_sales: "সাপ্তাহিক অফার",
    address: "ঠিকানা",
    address_val: "উত্তরা, ঢাকা, বাংলাদেশ",
    call_us: "কল করুন",
    mail: "ইমেইল",
    hours_label: "সময়সূচী",
    company: "কোম্পানি",
    about_us: "আমাদের সম্পর্কে",
    delivery_info: "ডেলিভারি সংক্রান্ত তথ্য",
    privacy_policy: "প্রাইভেসি পলিসি",
    data_deletion: "ডাটা ডিলিট পলিসি",
    terms_conditions: "শর্তাবলী ও নিয়ম",
    contact_us: "যোগাযোগ করুন",
    support_center: "সাপোর্ট সেন্টার",
    corporate: "কর্পোরেট",
    become_vendor: "ভেন্ডর হিসেবে যোগ দিন",
    affiliate_program: "অ্যাফিলিয়েট প্রোগ্রাম",
    farm_business: "কৃষি ব্যবসা",
    farm_careers: "ক্যারিয়ার",
    our_suppliers: "আমাদের সরবরাহকারী",
    accessibility: "অ্যাক্সেসিবিলিটি",
    promotions: "প্রমোশন",
    popular: "জনপ্রিয়",
    install_app: "অ্যাপ ইনস্টল করুন",
    from_app_store: "অ্যাপ স্টোর অথবা গুগল প্লে থেকে",
    secured_payment_gateways: "নিরাপদ পেমেন্ট গেটওয়ে",
    copyright: "সর্বস্বত্ব সংরক্ষিত",
    mens_tshirt: "পুরুষদের টি-শার্ট ও পোলো",
    mens_pant: "পুরুষদের প্যান্ট ও ট্রাউজার",
    electronics: "ইলেকট্রনিক্স ও গ্যাজেটস",
    fashion: "ফ্যাশন ও পোশাক",
    watches: "ঘড়ি ও গহনা",
    laptops: "ল্যাপটপ ও কম্পিউটার",
    beauty: "বিউটি ও স্কিনকেয়ার",
    audio: "হেডফোন ও অডিও",
    smartphones: "স্মার্টফোন",
    footwear: "জুতা ও স্যান্ডেল",
    groceries: "মুদি ও নিত্যপণ্য",
    home_living: "হোম ও লিভিং",
    super_discount: "সুপার ডিসকাউন্ট",
    summer_discount: "এই গরমে ৮০% পর্যন্ত ছাড়",
    exclusive_audio: "এক্সক্লুসিভ অডিও সেল",
    studio_headsets: "স্টুডিও হেডসেট",
    luxury_watches: "লাক্সারি স্মার্ট ওয়াচ",
    with_buying_fridge: "ফ্রিজ কিনলেই বিশেষ অফার",
    discount: "ডিসকাউন্ট",
    sale_up_to_60: "৫০+ পণ্যে ৬০% পর্যন্ত ছাড়",
    explore_now: "এখনই দেখুন",
    buy_now: "এখনই কিনুন",
    spring_season: "বসন্তের অফার",
    first_order: "প্রথম অর্ডারে",
    cameras: "ক্যামেরা",
    everything: "সবকিছুতেই!",
    case_iphone: "আইফোন কেস অফার",
    sitewide: "পুরো সাইট জুড়ে *",
    promo_code: "প্রোমো কোড",
    time: "সময়",
    cart_summary_msg: "অর্ডার সম্পন্ন করতে আর মাত্র কয়েকটি ধাপ বাকি।",
    cart_empty_msg: "আপনার কার্ট বর্তমানে খালি আছে। কিছু পণ্য যোগ করুন!",
    cart_empty: "কার্ট খালি",
    cart_empty_sub: "পণ্য দেখতে ক্যাটালগ থেকে কার্টে যোগ করুন।",
    price: "মূল্য",
    subtotal: "সাবটোটাল",
    total_items: "মোট পণ্য",
    units: "টি",
    total_price: "সর্বমোট মূল্য",
    checkout: "চেকআউট করুন",
    view_full_cart: "সম্পূর্ণ কার্ট দেখুন",
    tax_shipping_note: "ট্যাক্স ও ডেলিভারি চার্জ চেকআউটের সময় যুক্ত হবে।",
    wishlist_empty: "আপনার উইশলিস্ট খালি",
    save_items_love: "পছন্দের পণ্যগুলো উইশলিস্টে সংরক্ষণ করুন।",
    start_shopping: "কেনাকাটা শুরু করুন",
    item: "টি পণ্য",
    items: "টি পণ্য",
    clear_all: "সব মুছুন",
    removed_from_wishlist: "উইশলিস্ট থেকে সরানো হয়েছে",
    moved_to_cart: "কার্টে স্থানান্তর করা হয়েছে",
    wishlist_cleared: "উইশলিস্ট খালি করা হয়েছে",
    no_categories_found: "কোনো ক্যাটাগরি পাওয়া যায়নি",
    view_all_categories: "সকল ক্যাটাগরি দেখুন",
    menu: "মেনু",
    // Direct string phrase mappings for dynamic text lookups
    "flash sale": "ফ্ল্যাশ সেল",
    "all categories": "সকল ক্যাটাগরি",
    "all brands": "সকল ব্র্যান্ড",
    "weekly best product": "সাপ্তাহিক সেরা পণ্য",
    "featured products": "বিশেষ পণ্যসমূহ",
    "new arrivals": "নতুন পণ্য",
    "hot deals": "হট ডিলস",
    "deals of the day": "দিনের সেরা ডিল",
    "weekly top vendors": "সাপ্তাহিক সেরা ভেন্ডর",
    "featured sellers": "সেরা সেলারসমূহ",
    "top verified stores": "ভেরিফায়েড টপ স্টোর",
    "men's t-shirts & polos": "পুরুষদের টি-শার্ট ও পোলো",
    "men's pants & trousers": "পুরুষদের প্যান্ট ও ট্রাউজার",
    "electronics & gadgets": "ইলেকট্রনিক্স ও গ্যাজেটস",
    "fashion & apparel": "ফ্যাশন ও পোশাক",
    "watches & jewelry": "ঘড়ি ও গহনা",
    "laptops & tech": "ল্যাপটপ ও কম্পিউটার",
    "beauty & skincare": "বিউটি ও স্কিনকেয়ার",
    "headphones & audio": "হেডফোন ও অডিও",
    "shop by category": "ক্যাটাগরি অনুযায়ী কেনাকাটা",
    "view all products": "সব পণ্য দেখুন",
    "view all": "সব দেখুন",
    see_more: "আরও দেখুন",
    see_more_products: "আরও পণ্য দেখুন",
    "see more products": "আরও পণ্য দেখুন",
    "see more": "আরও দেখুন",
    "shop more": "আরও দেখুন",
    "shop now": "এখনই কিনুন",
    "show now": "এখনই কিনুন",
    "add to cart": "কার্টে যোগ করুন",
    "start seller": "সেলার শুরু করুন",
    "become a seller": "সেলার হোন",
    "join affiliate": "অ্যাফিলিয়েট",
    "customer support": "কাস্টমার সাপোর্ট",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    try {
      const savedLang = localStorage.getItem("lang") as Language;
      if (savedLang === "en" || savedLang === "bn") {
        setLanguageState(savedLang);
      } else {
        setLanguageState("en");
        localStorage.setItem("lang", "en");
      }
    } catch {
      setLanguageState("en");
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem("lang", lang);
      document.cookie = `NEXT_LOCALE=${lang}; path=/; max-age=31536000`;
    } catch (e) {
      console.error("Failed to save language preference", e);
    }
  };

  const t = (key: string, defaultText?: string) => {
    if (!key) return defaultText || "";
    if (language === "en") {
      return translations["en"]?.[key] || defaultText || key;
    }
    const cleanKey = key.trim();
    const lowerKey = cleanKey.toLowerCase();
    return (
      translations["bn"]?.[cleanKey] ||
      translations["bn"]?.[lowerKey] ||
      translations["bn"]?.[cleanKey.replace(/\s+/g, "_").toLowerCase()] ||
      defaultText ||
      key
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
